### ISSUE TITLE
None of the install options works

### ISSUE THREAD

**Issue by Stokestack** [BreezeWhite/oemer#22] opened 2023-05-17 23:56 UTC
I tried most of the listed options. Here's what I got (on Mac OS with latest PIP):

```
% pip install https://github.com/BreezeWhite/oemer
Collecting https://github.com/BreezeWhite/oemer
  Downloading https://github.com/BreezeWhite/oemer
     | 267.6 kB 1.7 MB/s 0:00:00
  ERROR: Cannot unpack file /private/var/folders/1m/7kvq_hrs6xj5sv81vhr4xdzw0000gn/T/pip-unpack-j391zrlr/oemer (downloaded from /private/var/folders/1m/7kvq_hrs6xj5sv81vhr4xdzw0000gn/T/pip-req-build-p3mx0c4v, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of /private/var/folders/1m/7kvq_hrs6xj5sv81vhr4xdzw0000gn/T/pip-req-build-p3mx0c4v


% pip install oemer
Collecting oemer
  Downloading oemer-0.1.5-py3-none-any.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 8.0 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of oemer to determine which version is compatible with other requirements. This could take a while.
  Downloading oemer-0.1.4-py3-none-any.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 15.3 MB/s eta 0:00:00
  Downloading oemer-0.1.3-py3-none-any.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 14.9 MB/s eta 0:00:00
  Downloading oemer-0.1.2-py3-none-any.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 19.0 MB/s eta 0:00:00
  Downloading oemer-0.1.1-py3-none-any.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 16.6 MB/s eta 0:00:00
  Downloading oemer-0.1.0-py3-none-any.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 15.6 MB/s eta 0:00:00
ERROR: Cannot install oemer==0.1.0, oemer==0.1.1, oemer==0.1.2, oemer==0.1.3, oemer==0.1.4 and oemer==0.1.5 because these package versions have conflicting dependencies.


% pip install oemer[full]
zsh: no matches found: oemer[full]
```

Then I downloaded the code and did:

```
Downloads/oemer-main % python ./setup.py install
```
And that seemed to go well until the end:

```
Installed /opt/homebrew/lib/python3.11/site-packages/opencv_python-4.7.0.72-py3.11-macosx-13-arm64.egg
Searching for onnxruntime
Reading https://pypi.org/simple/onnxruntime/
No local packages or working download links found for onnxruntime
error: Could not find suitable distribution for Requirement.parse('onnxruntime')
```

So then I tried:

```
 % pip install onnxruntime  
ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)
ERROR: No matching distribution found for onnxruntime
```

**Comment by BreezeWhite** [comment] 2023-05-18 04:08
I've done a little search and found the possible solution to install `onnxruntime` on a M-series Mac machine: https://github.com/microsoft/onnxruntime/issues/11037#issuecomment-1081420481. The approach is to use conda to install. You can give it a try.

**Comment by nghiap** [comment] 2023-06-28 00:59
I just want to say thank you for sharing your program on here.
I manage to have it working with the following method:
1) pip install oemer and run the oemer.exe afterward
2) by download your source code, run "setup.py install" and then run the ete.py file.
3) I also got it working using your google colab share
Fantastic work!!!   
I would like to get MP3 output like the google colab  for method 1 and 2 if you would be so kind to tell me how.
I have very little knowledge of coding so please give full steps if you are keen to help with this one.  

Once again - THANK YOU for a fantastic program.

**Comment by Stokestack** [comment] 2023-06-28 01:29
" run the oemer.exe afterward"

Mmm... that's not going to work on a Mac. But thanks.

**Comment by BreezeWhite** [comment] 2023-06-28 02:41
Hi @nghiap , thanks for your feedback and really encouraged me~^^

To get the MP3, you can just copy paste the code from colab, or alternatively using a GUI approach since looks like you are on a Windows platform, and using a GUI is more straight forward. For your convenience, here are rough steps to do it.

1. Download MuseScore from [here](https://musescore.org/en/download)
2. Open MuseScore
3. File -> Import -> Choose the transcribed sheet `.musicxml` file that is generated by `oemer`.
4. Agree with all warning messages and ignore them until you see the sheet shows up correctly.
5. File -> Export -> Choose format `MP3 audio` -> Export.

Hope above helps.
Enjoy your play~

**Comment by BreezeWhite** [comment] 2023-08-01 07:24
This should be fixed now. The problem is that currently there is no `onnxruntime-gpu` for Mac. I've updated the `setup.py`, specifying Mac to use `onnxruntime` instead.

**Closed by BreezeWhite** 2023-08-01 07:24 UTC

**Comment by Stokestack** [comment] 2023-08-01 22:30
pip install oemer

now works. Thanks!
